---
resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource

resources:
- name: trainingCICD
  type: pull-request
  check_every: 30m
  source:
    base_branch: ((git-branch))
    access_token: ((access_token))
    disable_ci_skip: true
    repository: ((git-repo))
    states:
      - OPEN

jobs:
- name: build-spring-boot
  plan:
  - get: trainingCICD
    trigger: true
    version: every
    params: { list_changed_files: true }
  - put: update-status
    resource: trainingCICD
    params:
      path: trainingCICD
      status: pending    
  - task: maven-build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: maven
          tag: "3.8.5-openjdk-17"
      inputs:
      - name: trainingCICD
      outputs:
      - name: build-artifacts
      run:
        path: /bin/bash
        args:
        - -c
        - |
          cd trainingCICD
          echo "Starting Maven build..."
          mvn clean install -B -DskipTests=false
          echo "Build completed successfully!"
          
          # Copy artifacts to output
          mkdir -p ../build-artifacts
          cp target/*.jar ../build-artifacts/ || echo "No JAR files found"
          cp pom.xml ../build-artifacts/
          
          echo "Build artifacts:"
          ls -la ../build-artifacts/
    on_success:
      do:
        - put: trainingCICD
          inputs: [ trainingCICD ]
          params:
            path: trainingCICD
            status: success
    on_failure:
      do:
        - put: trainingCICD
          params:
            path: trainingCICD
            status: failure